name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Логин в Docker Hub (если используете)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Сборка и публикация Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/laba_seti:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Деплой на удаленный сервер
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/laba_seti:latest
            docker stop laba_seti || true
            docker rm laba_seti || true
            docker run -d --name laba_seti -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/laba_seti:latest
          EOF
